### ISSUE TITLE
Making nodemaker production-ready

### ISSUE THREAD

**Issue by ivov** [ivov/nodemaker#1]
**Roadmap**

- [x] generate the node as `Service.node.ts`
- [x] generate the credential as `ServiceOAuth2Api.credential.ts` (OAuth2) or `ServiceApi.credential.ts` (API key)
- [x] generate both API request functions in `GenericFunctions.ts`
- [x] generate an updated `/packages/nodes-base/package.json`
- [x] generate separate files for resources with many operations and fields, as in `EntityDescription.ts`
- [x] migrate project to TypeScript to ensure type safety in params
- [x] convert project to OOP
- [x] place the generated files in their appropriate locations in the repo
- [x] document all major generator methods
- [x] ~~use additional fields in the node branches~~ → cannot be automated?
- [x] ~~handle errors based on error object~~ → cannot be automated?
- [x] ~~retrieve the next page in the all items request~~ → cannot be automated?
- [x] ~~check for total in all items request~~ → cannot be automated?
- [x] ~~fill in credential parameters~~ → cannot be automated?
- [x] generate five icon candidates
- [x] generate main docs file
- [x] place generated main docs file in its appropriate location in the docs repo
- [x] generate credentials docs file
- [x] place generated credentials docs file in its appropriate location in the docs repo
- [ ] generate workflow submission on n8n.io via Puppeteer
- [ ] generate workflow PNG via Puppeteer
- [x] resize selected icon to 60×60 pixels
- [x] place icon in its appropriate location in the n8n repo
- [ ] write tests!
- [x] write a comprehensive README

**Comment by ivov** [comment]
# Draft for Teamwork Roadmap 

## Frontend
- [ ] Webapp or desktop app?

## Functionality

### Minor tasks
  - [ ] `packgen` Check if node to be inserted already exists
  - [ ] `.hygen.js` Clean up helper functions
  - [ ] `.hygen.js` Convert helper functions to TypeScript
  - [ ] `Prompter.ts` Use enums as output types of inquirer prompts

### Major tasks
  - [ ] Testing for output files
  - [ ] Automate node screencap with Puppeteer → **WIP**
  - [ ] Automate [workflow creation](https://n8n.io/workflows) with Puppeteer and insert URL in doc file → **WIP**
  - [ ] Automate [pre-submission checks](https://github.com/n8n-io/n8n/blob/master/CONTRIBUTING.md#checklist-before-submitting-a-new-node)
  - [ ] Execute generated node, once placed in `n8n` repo, from inside `nodemaker`


### Tasks to be revisited
  - [ ] Use additional fields in the node branches
  - [ ] Handle errors based on error object 
  - [ ] Retrieve the next page in the all items request
  - [ ] Check for total in all items request 
  - [ ] Fill in credential parameters

**Comment by ivov** [comment]
Future work done in [MLH fork](https://github.com/MLH-Fellowship/nodemaker).
